title: fenglinliu
description: fenglinliu
name_pinyin: Fenglin Liu
name_chinese: 刘峰林
theme: jekyll-theme-dinky
email: fenglinliu98@pku.edu.cn
email_full: mailto:fenglinliu98@pku.edu.cn

aff1: LANCO,
aff1url: http://lanco.pku.edu.cn/
aff2: Peking University,
aff2url: http://www.pku.edu.cn/
aff3: Beijing University of Posts and Telecommunications,
aff3url: http://www.bupt.edu.cn/
